{% set name = "xarray-beam" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: df2d64bd6ce28a11a8eb652817b9d1a860b665fbb57e56e8a1d71a36bce8cbef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - apache-beam >=2.31.0
    - dask-core
    - immutabledict
    - python >=3.0
    - rechunker >=0.5.1
    - xarray
    - zarr

test:
  imports:
    - xarray_beam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xarray-beam
  summary: Distributed Xarray with Apache Beam
  description: Xarray-Beam is a Python library for building Apache Beam pipelines with Xarray datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxrjones
