{% set name = "xarray-beam" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-beam-{{ version }}.tar.gz
  sha256: 9d29cabe60a9416eb44d32a969d1bb9e6613f9f60084af673871a6fc0e72d47b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - apache-beam >=2.31.0
    - dask-core
    - immutabledict
    - python >=3.0
    - rechunker >=0.5.1
    - xarray
    - zarr

test:
  imports:
    - xarray_beam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xarray-beam
  summary: Distributed Xarray with Apache Beam
  description: Xarray-Beam is a Python library for building Apache Beam pipelines with Xarray datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxrjones
