{% set name = "xarray-beam" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a55bab78c2afb99c432f0d774f0e585f709cc331ca3dcfc93d6a1712a3d3042e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - apache-beam >=2.31.0
    - dask-core
    - immutabledict
    - python >=3.0
    - rechunker >=0.5.1
    - xarray
    - zarr

test:
  imports:
    - xarray_beam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xarray-beam
  summary: Distributed Xarray with Apache Beam
  description: Xarray-Beam is a Python library for building Apache Beam pipelines with Xarray datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxrjones
